/**
 * dsh-memory-fitting 构建脚本。
 *
 * 两个入口：
 *   node 侧：src/node/index.js → lib/index.js（ESM，宿主进程运行）
 *   client 侧：src/client/index.cjs → lib/client.js（CJS，浏览器运行）
 *
 * 规则（照抄 Reference 实现的既有坑）：
 *   - node 侧必须 external 掉 @deepseek-ai/*，否则会把宿主的 cordis 打进包
 *   - client 侧必须是 CJS，且 require 只能命中宿主 seed 表提供的模块，
 *     漏一个 require 会让整个插件加载失败
 */
import { build } from 'esbuild'
import { mkdir } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))
const outDir = resolve(root, 'lib')

/** 宿主在运行时提供的模块。其余一律打进 payload。 */
const HOST_PROVIDED = [
  'react',
  'react/jsx-runtime',
  'react-dom',
  'react-dom/client',
  '@deepseek-ai/cordis',
  '@deepseek-ai/dsh-client-ui-slots',
]

const PLUGIN_ID = '@a9i5k4/dsh-memory-fitting'

await mkdir(outDir, { recursive: true })

const shared = {
  bundle: true,
  sourcemap: false,
  logLevel: 'info',
  // 保留中文原文。默认 esbuild 会把非 ASCII 转成 \uXXXX 转义，
  // 产物变得不可读、也让基于字符串的回归断言失效（本轮踩过）。
  charset: 'utf8',
}

// ── node 半边 ────────────────────────────────────────────────────────────
await build({
  ...shared,
  entryPoints: [resolve(root, 'src/node/index.js')],
  outfile: resolve(outDir, 'index.js'),
  platform: 'node',
  target: 'node20',
  format: 'esm',
  external: ['@deepseek-ai/cordis', '@deepseek-ai/*'],
  banner: { js: '/* ' + PLUGIN_ID + ' — DSH host half. Generated by build.mjs, do not edit. */' },
})

// ── client 半边 ──────────────────────────────────────────────────────────
await build({
  ...shared,
  entryPoints: [resolve(root, 'src/client/index.cjs')],
  outfile: resolve(outDir, 'client.js'),
  platform: 'browser',
  target: 'es2020',
  format: 'cjs',
  external: HOST_PROVIDED,
  banner: {
    js:
      '/* ' + PLUGIN_ID + ' — browser half. Generated by build.mjs, do not edit. */\n' +
      'window.__ModuleLoader__.load({\n' +
      "  id: '" + PLUGIN_ID + "',\n" +
      '  factory: (require) => {\n' +
      '    var module = { exports: {} }; var exports = module.exports;',
  },
  footer: { js: '    return module.exports\n  }\n})' },
})

console.log('[memory-fitting] build done → lib/index.js, lib/client.js')
