/* @a9i5k4/dsh-memory-fitting — browser half. Generated by build.mjs, do not edit. */
window.__ModuleLoader__.load({
  id: '@a9i5k4/dsh-memory-fitting',
  factory: (require) => {
    var module = { exports: {} }; var exports = module.exports;

// src/client/index.cjs
var API = {
  state: "/api/memory-fitting/state",
  stats: "/api/memory-fitting/stats",
  config: "/api/memory-fitting/config",
  session: "/api/memory-fitting/session",
  deleteSession: "/api/memory-fitting/session",
  start: "/api/memory-fitting/start",
  archive: "/api/memory-fitting/archive",
  rename: "/api/memory-fitting/rename"
};
function req(path, opts) {
  return fetch(path, Object.assign({ headers: { "content-type": "application/json" } }, opts || {})).then(function(r) {
    return r.json();
  });
}
var state = {
  config: null,
  sessions: [],
  detected: null,
  alive: false,
  sanitize: null,
  stats: null,
  tab: "settings",
  detail: null,
  loading: true,
  error: null,
  toast: null,
  lastUtterance: "",
  confirmingDelete: null,
  editingTitle: null,
  open: false
};
var hostCtx = { workspace: "" };
var CSS_ID = "mf-style";
function ensureStyle() {
  if (document.getElementById(CSS_ID)) return;
  var s = document.createElement("style");
  s.id = CSS_ID;
  s.textContent = [
    ".mf-fab{position:fixed;right:16px;bottom:16px;z-index:9996;display:flex;align-items:center;gap:7px;",
    "padding:8px 13px;border-radius:12px;border:1px solid rgba(255,255,255,.16);cursor:pointer;",
    "background:rgba(28,30,36,.74);backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);",
    'color:#e8eaed;font:600 12px/1 system-ui,-apple-system,"Segoe UI",sans-serif;box-shadow:0 6px 20px rgba(0,0,0,.3);',
    "user-select:none;transition:background .15s}",
    ".mf-fab:hover{background:rgba(40,44,52,.86)}",
    ".mf-fab .mf-dot{width:7px;height:7px;border-radius:50%;background:#6b7280;transition:background .2s}",
    ".mf-fab.mf-on .mf-dot{background:#34d399}",
    ".mf-panel{position:fixed;right:472px;bottom:16px;z-index:9995;width:420px;max-width:calc(100vw - 508px);",
    "height:min(78vh,660px);display:none;flex-direction:column;overflow:hidden;border-radius:16px;",
    "border:1px solid rgba(255,255,255,.14);background:rgba(24,26,32,.88);backdrop-filter:blur(22px) saturate(1.3);",
    "-webkit-backdrop-filter:blur(22px) saturate(1.3);color:#e6e8ec;box-shadow:0 18px 50px rgba(0,0,0,.45);",
    'font:13px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif}',
    ".mf-hd{display:flex;align-items:center;gap:6px;padding:11px 13px;border-bottom:1px solid rgba(255,255,255,.09);flex-shrink:0}",
    ".mf-hd b{font-size:13px;font-weight:700;flex:1;letter-spacing:.2px}",
    ".mf-x{cursor:pointer;opacity:.55;padding:3px 7px;border-radius:7px;font-size:13px;line-height:1}",
    ".mf-x:hover{opacity:1;background:rgba(255,255,255,.09)}",
    ".mf-tabs{display:flex;gap:3px;padding:9px 13px 0;flex-shrink:0}",
    ".mf-tab{cursor:pointer;padding:6px 11px;border-radius:8px;font-size:12px;opacity:.6;font-weight:600;transition:all .13s}",
    ".mf-tab:hover{background:rgba(255,255,255,.06);opacity:.85}",
    ".mf-tab.on{background:rgba(96,165,250,.17);color:#bfdbfe;opacity:1}",
    ".mf-body{flex:1;overflow:auto;padding:11px 13px 16px;min-height:0}",
    ".mf-body::-webkit-scrollbar{width:8px}.mf-body::-webkit-scrollbar-thumb{background:rgba(255,255,255,.11);border-radius:4px}",
    ".mf-sec{margin-bottom:15px}",
    ".mf-sec h4{margin:0 0 7px;font-size:11.5px;font-weight:700;opacity:.62;letter-spacing:.4px;text-transform:uppercase}",
    ".mf-row{display:flex;align-items:center;gap:9px;padding:8px 9px;border-radius:10px;background:rgba(255,255,255,.035);margin-bottom:6px;transition:background .13s}",
    ".mf-row:hover{background:rgba(255,255,255,.055)}",
    ".mf-row .mf-t{flex:1;min-width:0}",
    ".mf-row .mf-t b{display:block;font-size:12.5px;font-weight:600;margin-bottom:1px}",
    ".mf-row .mf-t i{display:block;font-size:11px;opacity:.55;font-style:normal;line-height:1.45}",
    ".mf-sw{width:38px;height:21px;border-radius:11px;background:#3f4350;position:relative;cursor:pointer;flex-shrink:0;transition:background .16s}",
    ".mf-sw.on{background:#2563eb}",
    ".mf-sw i{position:absolute;top:2px;left:2px;width:17px;height:17px;border-radius:50%;background:#fff;transition:left .16s;box-shadow:0 1px 3px rgba(0,0,0,.3)}",
    ".mf-sw.on i{left:19px}",
    ".mf-btn{cursor:pointer;padding:6px 12px;border-radius:8px;border:1px solid rgba(255,255,255,.16);background:rgba(96,165,250,.16);color:#dbeafe;font-size:12px;font-weight:600;white-space:nowrap;user-select:none;transition:background .13s}",
    ".mf-btn:hover{background:rgba(96,165,250,.28)}",
    ".mf-btn:active{transform:translateY(1px)}",
    ".mf-btn.sec{background:rgba(255,255,255,.05);color:#cbd0d8}",
    ".mf-btn.sec:hover{background:rgba(255,255,255,.11)}",
    ".mf-btn.danger{background:rgba(239,68,68,.16);color:#fecaca;border-color:rgba(239,68,68,.3)}",
    ".mf-btn.danger:hover{background:rgba(239,68,68,.28)}",
    ".mf-btn[disabled]{opacity:.5;cursor:default}",
    ".mf-in{width:100%;box-sizing:border-box;padding:8px 10px;border-radius:9px;border:1px solid rgba(255,255,255,.14);",
    "background:rgba(0,0,0,.26);color:#e6e8ec;font:12.5px/1.55 inherit;resize:vertical;outline:none;transition:border-color .13s}",
    ".mf-in:focus{border-color:rgba(96,165,250,.55)}",
    ".mf-item{padding:9px 10px;border-radius:10px;background:rgba(255,255,255,.035);margin-bottom:7px;cursor:pointer;transition:background .13s}",
    ".mf-item:hover{background:rgba(255,255,255,.08)}",
    ".mf-item b{font-size:12.5px;display:block;margin-bottom:2px}",
    ".mf-item i{font-size:11px;opacity:.55;font-style:normal;display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}",
    ".mf-badge{display:inline-block;padding:1.5px 7px;border-radius:5px;font-size:10px;font-weight:600;background:rgba(255,255,255,.1);margin-left:6px;vertical-align:middle}",
    ".mf-badge.ok{background:rgba(52,211,153,.18);color:#6ee7b7}",
    ".mf-badge.warn{background:rgba(251,191,36,.18);color:#fcd34d}",
    ".mf-badge.mut{opacity:.6}",
    ".mf-mut{opacity:.55;font-size:11.5px;line-height:1.6}",
    ".mf-ev{padding:7px 9px;border-left:2px solid rgba(255,255,255,.14);margin-bottom:6px;font-size:11.5px;line-height:1.6;background:rgba(255,255,255,.02);border-radius:0 6px 6px 0}",
    ".mf-ev.time{opacity:.45;font-size:10.5px}",
    ".mf-err{color:#fca5a5;font-size:12px;padding:8px 10px;background:rgba(239,68,68,.1);border-radius:8px;margin-bottom:10px}",
    ".mf-empty{text-align:center;opacity:.45;font-size:12px;padding:34px 12px;line-height:1.7}",
    ".mf-toast{position:fixed;right:16px;bottom:60px;z-index:9999;padding:7px 13px;border-radius:9px;",
    "background:rgba(37,99,235,.94);color:#fff;font:600 12px/1.4 system-ui,sans-serif;box-shadow:0 8px 24px rgba(0,0,0,.35);max-width:320px}",
    ".mf-toast.err{background:rgba(220,38,38,.94)}",
    ".mf-flex{display:flex;gap:7px;align-items:center}",
    ".mf-sp{flex:1}",
    ".mf-confirm{padding:9px 10px;border-radius:10px;background:rgba(239,68,68,.1);border:1px solid rgba(239,68,68,.22);margin-bottom:7px}",
    ".mf-confirm .q{font-size:12px;margin-bottom:7px}",
    ".mf-ico{font-size:13px;opacity:.8;flex-shrink:0}"
  ].join("");
  document.head.appendChild(s);
}
function el(tag, cls, text) {
  var d = document.createElement(tag);
  if (cls) d.className = cls;
  if (text != null) d.textContent = text;
  return d;
}
var toastTimer = null;
function toast(msg, isErr) {
  var old = document.getElementById("mf-toast");
  if (old) old.remove();
  var d = el("div", "mf-toast" + (isErr ? " err" : ""), msg);
  d.id = "mf-toast";
  document.body.appendChild(d);
  clearTimeout(toastTimer);
  toastTimer = setTimeout(function() {
    d.remove();
  }, 3200);
}
function refresh() {
  return req(API.state).then(function(s) {
    if (s && s.ok) {
      state.config = s.config;
      state.sessions = s.sessions || [];
      state.detected = s.detected;
      state.alive = !!s.autoMemoryAlive;
      state.sanitize = s.sanitize;
      state.error = null;
    } else {
      state.error = s && s.error || "state 读取失败";
    }
    state.loading = false;
    render();
    req(API.stats).then(function(st) {
      if (st && st.ok) {
        state.stats = st;
        render();
      }
    }).catch(function() {
    });
  }).catch(function(e) {
    state.loading = false;
    state.error = String(e && e.message ? e.message : e);
    render();
  });
}
function setConfig(patch) {
  var prev = Object.assign({}, state.config);
  Object.assign(state.config, patch);
  render();
  return req(API.config, { method: "POST", body: JSON.stringify(patch) }).then(function(r) {
    if (r && r.ok) {
      state.config = r.config;
      render();
    } else {
      state.config = prev;
      render();
      toast("设置保存失败", true);
    }
  }).catch(function() {
    state.config = prev;
    render();
    toast("设置保存失败：网络错误", true);
  });
}
var panelRoot = null;
var panelHost = null;
var fabRoot = null;
function render() {
  if (!panelRoot || !panelHost) return;
  panelHost.innerHTML = "";
  panelHost.appendChild(renderHeader());
  panelHost.appendChild(renderTabs());
  var body = el("div", "mf-body");
  if (state.loading) body.appendChild(el("div", "mf-empty", "加载中…"));
  else {
    if (state.error) body.appendChild(el("div", "mf-err", "错误：" + state.error));
    if (state.tab === "settings") renderSettings(body);
    else if (state.tab === "archive") state.detail ? renderDetail(body) : renderArchive(body);
    else renderFit(body);
  }
  panelHost.appendChild(body);
}
function renderHeader() {
  var h = el("div", "mf-hd");
  h.appendChild(el("b", null, "记忆拟合"));
  var c = state.config || {};
  var inj = el("span", "mf-badge " + (c.injectContext ? "ok" : "mut"), "注入" + (c.injectContext ? "开" : "关"));
  h.appendChild(inj);
  var mem = el("span", "mf-badge " + (c.writeMemory ? "ok" : "mut"), "记忆" + (c.writeMemory ? "开" : "关"));
  h.appendChild(mem);
  var x = el("span", "mf-x", "✕");
  x.title = "收起（不影响后台留档）";
  x.onclick = function() {
    setOpen(false);
  };
  h.appendChild(x);
  return h;
}
function renderTabs() {
  var wrap = el("div", "mf-tabs");
  [["settings", "设置"], ["archive", "留档"], ["fit", "开始拟合"]].forEach(function(t) {
    var d = el("div", "mf-tab" + (state.tab === t[0] ? " on" : ""), t[1]);
    d.onclick = function() {
      state.tab = t[0];
      state.detail = null;
      state.confirmingDelete = null;
      render();
    };
    wrap.appendChild(d);
  });
  return wrap;
}
function switchRow(title, desc, key, extra) {
  var row = el("div", "mf-row");
  var t = el("div", "mf-t");
  t.appendChild(el("b", null, title));
  if (desc) t.appendChild(el("i", null, desc));
  row.appendChild(t);
  var on = !!(state.config && state.config[key]);
  var sw = el("div", "mf-sw" + (on ? " on" : ""));
  sw.appendChild(el("i"));
  sw.title = on ? "点击关闭" : "点击开启";
  sw.onclick = function() {
    var p = {};
    p[key] = !on;
    setConfig(p);
  };
  row.appendChild(sw);
  if (extra) row.appendChild(extra);
  return row;
}
function numRow(title, desc, key, min, max) {
  var row = el("div", "mf-row");
  var t = el("div", "mf-t");
  t.appendChild(el("b", null, title));
  t.appendChild(el("i", null, desc));
  row.appendChild(t);
  var inp = el("input", "mf-in");
  inp.type = "number";
  inp.min = String(min);
  inp.max = String(max);
  inp.value = String(state.config && state.config[key] || min);
  inp.style.width = "66px";
  inp.style.textAlign = "center";
  inp.onchange = function() {
    var v = Math.max(min, Math.min(Number(inp.value) || min, max));
    inp.value = String(v);
    var p = {};
    p[key] = v;
    setConfig(p);
  };
  row.appendChild(inp);
  return row;
}
function renderSettings(body) {
  var s1 = el("div", "mf-sec");
  s1.appendChild(el("h4", null, "污染面开关 · 默认关闭"));
  s1.appendChild(switchRow("注入会话上下文", "每轮注入一段极短说明，让模型知道可主动发起拟合。开启才有 token 开销", "injectContext"));
  s1.appendChild(switchRow("写入记忆插件", "把收敛结论写进 dsh-auto-memory。默认关闭以避免耦合", "writeMemory"));
  s1.appendChild(switchRow("向模型暴露工具", "模型可见 memory_fit_* 工具。注册即占每轮 tool 上下文", "exposeTools"));
  body.appendChild(s1);
  var s2 = el("div", "mf-sec");
  s2.appendChild(el("h4", null, "本插件自己的存储"));
  s2.appendChild(switchRow("本地留档", "拟合全过程写入 ~/.dsh/memory-fitting/sessions/（隔离于其它插件）", "localArchive"));
  s2.appendChild(switchRow("记住悬窗开合", "关闭则每次启动都收起悬窗", "persistPanelOpen"));
  body.appendChild(s2);
  var s3 = el("div", "mf-sec");
  s3.appendChild(el("h4", null, "拟合参数"));
  s3.appendChild(numRow("每轮问题数上限", "一轮最多问几个问题", "maxQuestionsPerRound", 1, 8));
  s3.appendChild(numRow("整场轮数上限", '防止"问上瘾"，默认 4 轮封顶', "maxRounds", 1, 12));
  body.appendChild(s3);
  var s4 = el("div", "mf-sec");
  s4.appendChild(el("h4", null, "环境自检"));
  var d = state.detected || {};
  var amText = d.autoMemory ? state.alive ? "已检测到 · 实例存活" : "已检测到 · 实例未响应" : "未检测到（不影响本地留档）";
  var r1 = el("div", "mf-row");
  var t1 = el("div", "mf-t");
  t1.appendChild(el("b", null, "dsh-auto-memory"));
  t1.appendChild(el("i", null, amText));
  r1.appendChild(t1);
  r1.appendChild(el("span", "mf-badge " + (state.alive ? "ok" : "mut"), state.alive ? "OK" : "—"));
  s4.appendChild(r1);
  var st = state.sanitize;
  if (st) {
    var good = st.detectionWorks && st.cleanHasNoReserved && st.contentPreserved && st.noopOnClean;
    var r2 = el("div", "mf-row");
    var t2 = el("div", "mf-t");
    t2.appendChild(el("b", null, "写入安全带"));
    t2.appendChild(el("i", null, "归档前对用户原话做字符级改写，防止锚点击穿记忆文件"));
    r2.appendChild(t2);
    r2.appendChild(el("span", "mf-badge " + (good ? "ok" : "warn"), good ? "通过" : "异常"));
    s4.appendChild(r2);
  }
  body.appendChild(s4);
}
function statusBadge(s) {
  var map = { accepted: "ok", proposed: "warn", fitting: "mut", dismissed: "mut" };
  var label = { accepted: "已确认", proposed: "待确认", fitting: "进行中", dismissed: "已放弃" };
  return el("span", "mf-badge " + (map[s] || "mut"), label[s] || s);
}
function renderArchive(body) {
  if (state.stats && state.stats.sessions > 0) {
    var card = el("div", "mf-row");
    var t = el("div", "mf-t");
    var answered = state.stats.answered || 0;
    var rate = Math.round((state.stats.correctionRate || 0) * 100);
    t.appendChild(el("b", null, "已答 " + answered + " 题 · 纠正率 " + rate + "%"));
    t.appendChild(el("i", null, rate >= 20 ? "样本有信息量（纠正率越高越值得训练）" : "纠正率偏低 —— 说明模型大多猜对了，样本信息量有限"));
    card.appendChild(t);
    body.appendChild(card);
  }
  var top = el("div", "mf-flex");
  top.style.marginBottom = "10px";
  var cnt = state.sessions.length;
  top.appendChild(el("div", "mf-mut", cnt ? "共 " + cnt + " 条留档" : ""));
  top.appendChild(el("div", "mf-sp"));
  var rb = el("div", "mf-btn sec", "刷新");
  rb.onclick = function() {
    state.loading = true;
    render();
    refresh();
  };
  top.appendChild(rb);
  body.appendChild(top);
  if (!state.sessions.length) {
    body.appendChild(el("div", "mf-empty", "还没有留档。\n到「开始拟合」页发起一次。"));
    return;
  }
  state.sessions.forEach(function(s) {
    var it = el("div", "mf-item");
    var b = el("b", null, s.title || s.conclusion && s.conclusion.winner || "（未收敛）");
    b.appendChild(statusBadge(s.status));
    it.appendChild(b);
    var when = String(s.createdAt || "").slice(0, 16).replace("T", " ");
    it.appendChild(el("i", null, when + " · " + String(s.utterance || "（无触发语）").slice(0, 44)));
    it.onclick = function() {
      state.loading = true;
      render();
      req(API.session + "?id=" + encodeURIComponent(s.id)).then(function(r) {
        state.loading = false;
        state.detail = r && r.ok ? r : { error: r && r.error || "读取失败" };
        render();
      }).catch(function(e) {
        state.loading = false;
        state.detail = { error: String(e) };
        render();
      });
    };
    body.appendChild(it);
  });
}
function renderDetail(body) {
  var back = el("div", "mf-btn sec", "← 返回列表");
  back.style.marginBottom = "11px";
  back.onclick = function() {
    state.detail = null;
    state.confirmingDelete = null;
    render();
  };
  body.appendChild(back);
  var d = state.detail;
  if (!d || d.error) {
    body.appendChild(el("div", "mf-err", "读取失败：" + (d && d.error || "unknown")));
    return;
  }
  var e = d.entry || {};
  var head = el("div", "mf-sec");
  var hb = el("div", "mf-flex");
  hb.appendChild(el("b", null, e.title || (e.conclusion && e.conclusion.winner || "（未收敛）")));
  hb.appendChild(el("div", "mf-sp"));
  hb.appendChild(statusBadge(e.status));
  head.appendChild(hb);
  if (e.utterance) head.appendChild(el("div", "mf-mut", "触发语：「" + e.utterance + "」"));
  if (e.workspace) head.appendChild(el("div", "mf-mut", "工作区：" + e.workspace));
  head.appendChild(el("div", "mf-mut", "创建于 " + String(e.createdAt || "").slice(0, 19).replace("T", " ")));
  body.appendChild(head);
  var act = el("div", "mf-flex");
  act.style.marginBottom = "13px";
  if (e.status !== "accepted" && e.conclusion && e.conclusion.winner) {
    var okBtn = el("div", "mf-btn", "确认并归档");
    okBtn.onclick = function() {
      okBtn.textContent = "归档中…";
      req(API.archive, { method: "POST", body: JSON.stringify({ sessionId: e.id, winner: e.conclusion.winner, accepted: true }) }).then(function(r) {
        if (r && r.ok) {
          toast(r.writeMemory ? r.external && r.external.ok ? "已归档（含写入记忆插件）" : "已本地归档；记忆插件写入失败：" + (r.external && r.external.reason || "未知") : "已本地归档（记忆写入开关关闭）");
          state.detail = null;
          state.tab = "archive";
          refresh();
        } else {
          toast("归档失败", true);
          okBtn.textContent = "确认并归档";
        }
      }).catch(function() {
        toast("归档失败：网络错误", true);
        okBtn.textContent = "确认并归档";
      });
    };
    act.appendChild(okBtn);
  }
  var renBtn = el("div", "mf-btn sec", "改标题");
  renBtn.onclick = function() {
    var t = prompt("给这条留档起个可读标题（拟合后回填节点名）", e.title || "");
    if (t == null) return;
    req(API.rename, { method: "POST", body: JSON.stringify({ sessionId: e.id, title: String(t).slice(0, 120) }) }).then(function() {
      state.detail = null;
      refresh();
      toast("标题已更新");
    });
  };
  act.appendChild(renBtn);
  if (state.confirmingDelete === e.id) {
    var cf = el("div", "mf-confirm");
    cf.appendChild(el("div", "q", "删除这条留档？会话文件与索引项都会被移除，不可恢复。"));
    var cb = el("div", "mf-flex");
    var y = el("div", "mf-btn danger", "确认删除");
    y.onclick = function() {
      y.textContent = "删除中…";
      fetch(API.deleteSession + "?id=" + encodeURIComponent(e.id), { method: "DELETE" }).then(function(r) {
        return r.json();
      }).then(function(r) {
        if (r && r.ok) {
          toast("已删除");
          state.detail = null;
          state.confirmingDelete = null;
          refresh();
        } else {
          toast("删除失败：" + (r && r.reason || "未知"), true);
          render();
        }
      }).catch(function() {
        toast("删除失败", true);
        render();
      });
    };
    cb.appendChild(y);
    var n = el("div", "mf-btn sec", "取消");
    n.onclick = function() {
      state.confirmingDelete = null;
      render();
    };
    cb.appendChild(n);
    cf.appendChild(cb);
    act.appendChild(el("div", "mf-sp"));
    act.appendChild(cf);
    body.appendChild(act);
    return;
  }
  var delBtn = el("div", "mf-btn danger", "删除");
  delBtn.onclick = function() {
    state.confirmingDelete = e.id;
    render();
  };
  act.appendChild(delBtn);
  body.appendChild(act);
  var events = d.events || [];
  var sec = el("div", "mf-sec");
  sec.appendChild(el("h4", null, "事件流 · " + events.length + " 帧"));
  if (!events.length) sec.appendChild(el("div", "mf-mut", "（空）"));
  events.forEach(function(ev) {
    var line = el("div", "mf-ev");
    var txt = "";
    if (ev.type === "fit/start") txt = "▶ 开始 · 工作区 " + (ev.workspace || "—");
    else if (ev.type === "fit/directions") txt = "◇ 预定方向：" + (ev.directions || []).map(function(x) {
      return x.label;
    }).join(" / ");
    else if (ev.type === "fit/ask") txt = "？ 第" + ev.round + "轮提问：" + (ev.questions || []).map(function(q) {
      return q.question;
    }).join("；");
    else if (ev.type === "fit/answer") txt = "✓ 第" + ev.round + "轮作答：" + (ev.summary || "");
    else if (ev.type === "fit/reflect") txt = "⟳ 轮间思考：" + ((ev.directions || []).map(function(x) {
      return x.label;
    }).join(" / ") || ev.rationale || "");
    else if (ev.type === "fit/propose") txt = "★ 收敛提案：" + (ev.conclusion && ev.conclusion.winner || "");
    else if (ev.type === "fit/finish") txt = (ev.accepted ? "✔ 用户确认" : "✗ 用户放弃") + (ev.note ? " · " + ev.note : "");
    else if (ev.type === "fit/feedback") txt = "◎ 反馈（" + ev.verdict + "）：" + (ev.preference || "");
    else txt = ev.type;
    line.textContent = txt;
    sec.appendChild(line);
  });
  body.appendChild(sec);
}
function renderFit(body) {
  var sec = el("div", "mf-sec");
  sec.appendChild(el("h4", null, "发起一次拟合"));
  sec.appendChild(el("div", "mf-mut", "写下触发语 → 开始 → 到聊天窗口回答模型提出的问题。"));
  var ta = el("textarea", "mf-in");
  ta.rows = 3;
  ta.placeholder = "例如：帮我把记忆这部分弄好一点，感觉不太行。";
  ta.value = state.lastUtterance || "";
  ta.oninput = function() {
    state.lastUtterance = ta.value;
  };
  sec.appendChild(ta);
  body.appendChild(sec);
  var row = el("div", "mf-row");
  var t = el("div", "mf-t");
  t.appendChild(el("b", null, "立即开始"));
  t.appendChild(el("i", null, "在本地建立拟合会话并记入留档"));
  row.appendChild(t);
  var btn = el("div", "mf-btn", "开始");
  btn.onclick = function() {
    var u = (ta.value || "").trim();
    if (!u) {
      toast("请先写下触发语", true);
      return;
    }
    btn.textContent = "创建中…";
    btn.setAttribute("disabled", "1");
    req(API.start, { method: "POST", body: JSON.stringify({ utterance: u, workspace: hostCtx.workspace || "" }) }).then(function(r) {
      btn.textContent = "开始";
      btn.removeAttribute("disabled");
      if (r && r.ok) {
        toast("拟合会话已建立：" + (r.session && r.session.id));
        state.lastUtterance = "";
        state.tab = "archive";
        state.detail = null;
        refresh();
      } else {
        toast("创建失败：" + (r && r.error || "未知"), true);
      }
    }).catch(function(e) {
      btn.textContent = "开始";
      btn.removeAttribute("disabled");
      toast("创建失败：" + e, true);
    });
  };
  row.appendChild(btn);
  body.appendChild(row);
  var hint = el("div", "mf-sec");
  hint.appendChild(el("h4", null, "让 AI 主动发起"));
  var toolsOn = state.config && state.config.exposeTools;
  hint.appendChild(el("div", "mf-mut", toolsOn ? "已开启工具暴露：直接对 AI 说「我还没想清楚，帮我拟合一下意图」即可。" : "工具暴露当前关闭（默认）。到设置页打开「向模型暴露工具」，或直接在本页发起。"));
  body.appendChild(hint);
  var flow = el("div", "mf-sec");
  flow.appendChild(el("h4", null, "拟合流程"));
  flow.appendChild(el("div", "mf-mut", '① AI 预定 3-5 个方向（预测你的意图）\n② 每轮针对"分不开的方向"提 2-4 个问题\n③ 一次问一批，你逐个作答\n④ 轮间思考并展示方向可信度\n⑤ 收敛后提案，你确认 → 归档'));
  body.appendChild(flow);
}
function ensureMounted() {
  ensureStyle();
  if (!fabRoot || !document.getElementById("mf-fab-root")) {
    fabRoot = document.createElement("div");
    fabRoot.id = "mf-fab-root";
    fabRoot.className = "mf-fab";
    fabRoot.appendChild(el("span", "mf-dot"));
    fabRoot.appendChild(el("span", null, "记忆拟合"));
    fabRoot.title = "记忆拟合";
    fabRoot.onclick = function() {
      setOpen(!state.open);
    };
    document.body.appendChild(fabRoot);
  }
  if (!panelRoot || !document.getElementById("mf-panel-root")) {
    panelRoot = document.createElement("div");
    panelRoot.id = "mf-panel-root";
    panelRoot.className = "mf-panel";
    panelHost = document.createElement("div");
    panelHost.style.cssText = "display:flex;flex-direction:column;height:100%;min-height:0";
    panelRoot.appendChild(panelHost);
    document.body.appendChild(panelRoot);
  }
}
function setOpen(v, silent) {
  ensureMounted();
  state.open = !!v;
  panelRoot.style.display = v ? "flex" : "none";
  if (fabRoot) fabRoot.className = "mf-fab" + (v ? " mf-on" : "");
  if (v) refresh();
  if (!silent) {
    var c = state.config;
    if (c && c.persistPanelOpen) setConfig({ panelOpenByDefault: !!v });
  }
}
function fitPanel() {
  if (!panelRoot) return;
  var w = window.innerWidth || 1200;
  if (w < 900) {
    panelRoot.style.right = "16px";
    panelRoot.style.width = "min(420px, calc(100vw - 32px))";
  } else {
    panelRoot.style.right = "472px";
    panelRoot.style.width = "420px";
  }
}
function apply(ctx) {
  ensureMounted();
  fitPanel();
  try {
    var sessions = typeof ctx.get === "function" ? ctx.get("sessions") : null;
    if (sessions && typeof sessions.getSnapshot === "function") {
      var snap = sessions.getSnapshot();
      var cur = snap && snap.current;
      if (cur && cur.cwd) hostCtx.workspace = String(cur.cwd);
    }
  } catch (e) {
  }
  window.addEventListener("resize", fitPanel);
  refresh().then(function() {
    if (state.config && state.config.panelOpenByDefault) setOpen(true, true);
  });
  try {
    var slots = ctx.slots;
    if (slots && typeof slots.inject === "function") {
      slots.inject("settings.section", function() {
        return slots.register(
          { name: "settings.section", id: "memory-fitting-pre", order: 33, label: "记忆拟合" },
          function() {
            var host = document.createElement("div");
            host.style.cssText = "padding:4px 2px 12px;color:inherit";
            var saveHost = panelHost;
            var tmp = document.createElement("div");
            tmp.className = "mf-body";
            tmp.style.cssText = "overflow:visible;padding:0;max-height:none";
            panelHost = tmp;
            render();
            panelHost = saveHost;
            host.appendChild(tmp);
            return host;
          }
        );
      });
    }
  } catch (e) {
    console.error("[memory-fitting] settings.section 注册失败:", e);
  }
  console.log("[memory-fitting] client ready");
}
module.exports = { apply };
    return module.exports
  }
})
