/* @a9i5k4/dsh-memory-fitting — DSH host half. Generated by build.mjs, do not edit. */

// src/node/store.js
import { readFile, writeFile, mkdir, readdir, appendFile, rename, unlink } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { randomBytes } from "node:crypto";
function rootDir() {
  return join(homedir(), ".dsh", "memory-fitting");
}
function sessionsDir() {
  return join(rootDir(), "sessions");
}
function configPath() {
  return join(rootDir(), "config.json");
}
function indexPath() {
  return join(sessionsDir(), "index.json");
}
var DEFAULT_CONFIG = {
  // 是否允许把拟合状态注入到会话上下文（污染面 1）
  injectContext: false,
  // 是否把收敛结论写入记忆插件（污染面 2）
  writeMemory: false,
  // 是否注册模型可见的工具（注册即每轮占 tool schema 上下文）
  exposeTools: false,
  // 插件自己的本地留档（用户选择处可开）
  localArchive: true,
  // 悬窗 UI
  panelOpenByDefault: false,
  // 记住悬窗上次的开合状态（关掉则每次重启都收起）
  persistPanelOpen: true,
  // 每轮最多几个问题 / 整场最多几轮
  maxQuestionsPerRound: 4,
  maxRounds: 4
};
var cachedConfig = null;
async function readConfig() {
  if (cachedConfig) return cachedConfig;
  try {
    const raw = await readFile(configPath(), "utf8");
    const parsed = JSON.parse(raw.replace(/^\uFEFF/, ""));
    cachedConfig = { ...DEFAULT_CONFIG, ...parsed };
  } catch {
    cachedConfig = { ...DEFAULT_CONFIG };
  }
  return cachedConfig;
}
async function writeConfig(patch) {
  const cur = await readConfig();
  const next = { ...cur, ...patch };
  await mkdir(rootDir(), { recursive: true });
  await writeFile(configPath(), JSON.stringify(next, null, 2) + "\n", "utf8");
  cachedConfig = next;
  return next;
}
function newSessionId() {
  return "fit_" + randomBytes(6).toString("hex");
}
function stamp() {
  const d = /* @__PURE__ */ new Date();
  const p = (n) => String(n).padStart(2, "0");
  return String(d.getFullYear()) + p(d.getMonth() + 1) + p(d.getDate()) + "-" + p(d.getHours()) + p(d.getMinutes()) + p(d.getSeconds());
}
async function createSession(meta) {
  await mkdir(sessionsDir(), { recursive: true });
  const id = meta.id || newSessionId();
  const file = join(sessionsDir(), stamp() + "-" + id + ".jsonl");
  const sess = {
    id,
    file,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    workspace: meta.workspace || null,
    utterance: meta.utterance || "",
    anchor: meta.anchor || null,
    rounds: [],
    directions: [],
    status: "fitting",
    conclusion: null
  };
  await appendEvent(sess, { type: "fit/start", workspace: sess.workspace, utterance: sess.utterance, anchor: sess.anchor });
  return sess;
}
async function appendEvent(sess, event) {
  const line = JSON.stringify({ t: (/* @__PURE__ */ new Date()).toISOString(), ...event }) + "\n";
  await appendFile(sess.file, line, "utf8");
}
async function upsertIndex(sess) {
  const idx = await listSessions();
  const prev = idx.find((x) => x.id === sess.id) || {};
  const entry = {
    id: sess.id,
    file: sess.file,
    createdAt: sess.createdAt,
    updatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    workspace: sess.workspace,
    utterance: sess.utterance,
    status: sess.status,
    rounds: sess.rounds.length,
    conclusion: sess.conclusion,
    // 保留用户手动补的标题（拟合后回填节点名）
    title: prev.title || null
  };
  const i = idx.findIndex((x) => x.id === sess.id);
  if (i >= 0) idx[i] = entry;
  else idx.unshift(entry);
  await writeIndex(idx);
  return idx;
}
async function writeIndex(idx) {
  await mkdir(sessionsDir(), { recursive: true });
  const trimmed = (Array.isArray(idx) ? idx : []).slice(0, 200);
  const tmp = indexPath() + ".tmp";
  await writeFile(tmp, JSON.stringify(trimmed, null, 2) + "\n", "utf8");
  await rename(tmp, indexPath());
  return trimmed;
}
async function deleteSession(id) {
  if (!id) return { ok: false, reason: "missing-id" };
  const idx = await listSessions();
  const entry = idx.find((x) => x.id === id);
  if (!entry) return { ok: false, reason: "not-found" };
  try {
    if (entry.file && existsSync(entry.file)) await unlink(entry.file);
  } catch (e) {
    return { ok: false, reason: "unlink-failed: " + (e && e.message) };
  }
  await writeIndex(idx.filter((x) => x.id !== id));
  return { ok: true, id };
}
async function listSessions() {
  try {
    const idx = JSON.parse((await readFile(indexPath(), "utf8")).replace(/^\uFEFF/, ""));
    return Array.isArray(idx) ? idx : [];
  } catch {
    return [];
  }
}
async function readSession(file) {
  try {
    const raw = await readFile(file, "utf8");
    return raw.split("\n").filter((l) => l.trim()).map((l) => {
      try {
        return JSON.parse(l);
      } catch {
        return null;
      }
    }).filter(Boolean);
  } catch {
    return [];
  }
}

// src/node/fitting.js
async function beginFitting({ workspace, utterance, anchor }) {
  const sess = await createSession({ workspace, utterance, anchor });
  await upsertIndex(sess);
  return sess;
}
async function recordDirections(sess, directions) {
  sess.directions = (directions || []).map((d, i) => ({
    id: d.id || "d" + (i + 1),
    label: String(d.label || "").slice(0, 120),
    detail: d.detail ? String(d.detail).slice(0, 400) : "",
    confidence: typeof d.confidence === "number" ? d.confidence : null
  }));
  await appendEvent(sess, { type: "fit/directions", directions: sess.directions });
  await upsertIndex(sess);
  return sess.directions;
}
async function recordQuestions(sess, questions) {
  const round = {
    index: sess.rounds.length + 1,
    questions: (questions || []).map((q, i) => ({
      id: q.id || "q" + (i + 1),
      question: String(q.question || "").slice(0, 500),
      options: Array.isArray(q.options) ? q.options.slice(0, 8).map((o) => ({ label: String(o.label || o).slice(0, 120) })) : [],
      multiSelect: !!q.multi_select
    })),
    answers: null,
    summary: ""
  };
  sess.rounds.push(round);
  await appendEvent(sess, { type: "fit/ask", round: round.index, questions: round.questions });
  await upsertIndex(sess);
  return round;
}
async function recordAnswers(sess, roundIndex, answers) {
  const round = sess.rounds.find((r) => r.index === roundIndex) || sess.rounds[sess.rounds.length - 1];
  if (!round) return null;
  round.answers = (answers || []).map((a) => ({
    id: a.id,
    selected: Array.isArray(a.selected) ? a.selected.map(String) : [],
    custom: a.custom ? String(a.custom).slice(0, 500) : null
  }));
  round.summary = round.questions.map((q) => {
    const a = round.answers.find((x) => x.id === q.id);
    const picked = a ? a.custom || (a.selected || []).join("、") : "（未答）";
    return q.question + " → " + picked;
  }).join("；");
  await appendEvent(sess, { type: "fit/answer", round: roundIndex, answers: round.answers, summary: round.summary });
  await upsertIndex(sess);
  return round;
}
async function propose(sess, conclusion) {
  sess.conclusion = {
    winner: String(conclusion.winner || "").slice(0, 200),
    confidence: typeof conclusion.confidence === "number" ? conclusion.confidence : null,
    intent: conclusion.intent ? String(conclusion.intent).slice(0, 500) : "",
    action: conclusion.action ? String(conclusion.action).slice(0, 500) : "",
    text: conclusion.text ? String(conclusion.text).slice(0, 800) : ""
  };
  sess.status = "proposed";
  await appendEvent(sess, { type: "fit/propose", conclusion: sess.conclusion });
  await upsertIndex(sess);
  return sess.conclusion;
}
async function finish(sess, { accepted, note }) {
  sess.status = accepted ? "accepted" : "dismissed";
  await appendEvent(sess, { type: "fit/finish", accepted: !!accepted, note: note ? String(note).slice(0, 500) : "" });
  await upsertIndex(sess);
  return sess;
}
async function recordFeedback(sess, {
  context,
  modelDid,
  userSaid,
  verdict,
  preference,
  scope,
  rejectedReason,
  deliberate
} = {}) {
  await appendEvent(sess, {
    type: "fit/feedback",
    context: String(context || "").slice(0, 800),
    modelDid: String(modelDid || "").slice(0, 800),
    userSaid: String(userSaid || "").slice(0, 800),
    verdict: ["accepted", "corrected", "rejected"].includes(verdict) ? verdict : "accepted",
    preference: String(preference || "").slice(0, 400),
    // ── 训练就绪字段（见 docs/TRAINING.md 阶段 1）──
    // scope: intent = 可进画像 / fact = 只走纠正通道。训练时【只取 intent】，
    //        否则会把用户的事实性错误学成偏好 → 谄媚。
    scope: scope === "fact" ? "fact" : "intent",
    // rejectedReason: 提案被拒时"错在哪"。比单纯 rejected 更有信息量。
    rejectedReason: rejectedReason ? String(rejectedReason).slice(0, 400) : null,
    // deliberate: 用户是深思熟虑还是随手一点。用于样本质量分层。
    deliberate: deliberate === false ? false : true
  });
  return true;
}

// src/node/log.js
var PREFIX = "[memory-fitting]";
function log(...args) {
  console.log(PREFIX, ...args);
}
function warn(...args) {
  console.warn(PREFIX, ...args);
}
function error(...args) {
  console.error(PREFIX, ...args);
}
function guard(label, fn) {
  return async (...args) => {
    try {
      return await fn(...args);
    } catch (e) {
      error(label + " failed:", e && e.stack ? e.stack : e);
      return void 0;
    }
  };
}

// src/node/memory-adapter.js
import { readFile as readFile2 } from "node:fs/promises";
import { join as join2 } from "node:path";
import { homedir as homedir2 } from "node:os";

// src/node/sanitize.js
var LT = String.fromCharCode(60);
var BANG = "!";
var DASH2 = "--";
var KEYWORD = "memory";
var COLON = ":";
var RESERVED_OPEN = LT + BANG + DASH2 + " " + KEYWORD + COLON;
function containsReserved(text) {
  return typeof text === "string" && text.includes(RESERVED_OPEN);
}
function sanitizeForMemory(text) {
  if (typeof text !== "string") return "";
  if (!containsReserved(text)) return text;
  return text.split(RESERVED_OPEN).join("［记忆锚点起始标记］");
}
function guard2(text) {
  const hits = typeof text === "string" ? text.split(RESERVED_OPEN).length - 1 : 0;
  return { ok: hits === 0, text: sanitizeForMemory(text), hits };
}
function selfTest() {
  const dirty = "x " + RESERVED_OPEN + " y";
  const clean = sanitizeForMemory(dirty);
  return {
    detectionWorks: containsReserved(dirty),
    cleanHasNoReserved: !containsReserved(clean),
    contentPreserved: clean.includes("x ") && clean.includes(" y"),
    noopOnClean: sanitizeForMemory("hello world") === "hello world"
  };
}

// src/node/memory-adapter.js
var PROFILE_MANIFEST = join2(homedir2(), ".dsh", "profiles", "web", "package.json");
async function detectMemoryPlugins() {
  const found = { autoMemory: false, bundles: [], dependencies: [] };
  try {
    const raw = await readFile2(PROFILE_MANIFEST, "utf8");
    const pkg = JSON.parse(raw.replace(/^\uFEFF/, ""));
    const deps = Object.keys(pkg.dependencies || {});
    const bundles = pkg.dsh && pkg.dsh.profile && pkg.dsh.profile.bundles || [];
    found.dependencies = deps;
    found.bundles = bundles;
    found.autoMemory = deps.includes("@a9i5k4/dsh-auto-memory") || bundles.includes("@a9i5k4/dsh-auto-memory");
  } catch {
  }
  return found;
}
async function autoMemoryAlive(port = 3080) {
  try {
    const ctrl = new AbortController();
    const t = setTimeout(() => ctrl.abort(), 1500);
    const res = await fetch("http://127.0.0.1:" + port + "/api/dsh-auto-memory-pre/state", { signal: ctrl.signal });
    clearTimeout(t);
    return res.ok;
  } catch {
    return false;
  }
}
async function writeToAutoMemory(content, port = 3080) {
  const g = guard2(String(content || ""));
  if (!g.text.trim()) return { ok: false, reason: "empty" };
  try {
    const ctrl = new AbortController();
    const t = setTimeout(() => ctrl.abort(), 8e3);
    const res = await fetch("http://127.0.0.1:" + port + "/api/dsh-auto-memory-pre/note", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ content: g.text }),
      signal: ctrl.signal
    });
    clearTimeout(t);
    return { ok: res.ok, status: res.status, sanitized: g.hits, reason: res.ok ? null : "http-" + res.status };
  } catch (e) {
    return { ok: false, reason: "network: " + (e && e.message ? e.message : String(e)) };
  }
}
function buildConclusionNote(sess, extra = {}) {
  const safe = (s) => guard2(String(s == null ? "" : s)).text;
  const lines = [];
  lines.push("### " + (safe(sess.anchor && sess.anchor.node) || "意图拟合结论"));
  lines.push("");
  if (sess.utterance) lines.push("- 触发语：「" + safe(sess.utterance) + "」");
  if (sess.workspace) lines.push("- 工作区：" + safe(sess.workspace));
  if (sess.anchor && sess.anchor.node) lines.push("- 节点：" + safe(sess.anchor.node));
  if (sess.conclusion) {
    lines.push("- 收敛方向：**" + safe(sess.conclusion.winner) + "**");
    if (typeof sess.conclusion.confidence === "number") {
      lines.push("- 置信度：" + sess.conclusion.confidence.toFixed(2));
    }
  }
  if (sess.directions && sess.directions.length) {
    lines.push("- 拟合方向：" + sess.directions.map((d) => safe(d.label || d.id)).join(" / "));
  }
  const rounds = sess.rounds || [];
  if (rounds.length) {
    lines.push("- 问答轨迹：");
    for (let i = 0; i < rounds.length; i++) {
      const r = rounds[i];
      lines.push("  " + (i + 1) + ". " + safe(r.summary || (r.questions || []).map((q) => q.question).join("；")));
    }
  }
  if (extra.note) lines.push("- " + safe(extra.note));
  return lines.join("\n");
}

// src/node/routes.js
var PREFIX2 = "/api/memory-fitting";
function pathOf(req) {
  const u = new URL(req.url ?? "/", "http://127.0.0.1");
  return u.pathname;
}
function writeJson(res, code, body) {
  res.statusCode = code;
  res.setHeader("content-type", "application/json; charset=utf-8");
  res.setHeader("cache-control", "no-store");
  res.end(JSON.stringify(body));
}
function readBody(req) {
  return new Promise((resolve) => {
    let raw = "";
    req.on("data", (c) => {
      raw += c;
      if (raw.length > 1e6) req.destroy();
    });
    req.on("end", () => {
      try {
        resolve(raw ? JSON.parse(raw) : {});
      } catch {
        resolve({});
      }
    });
    req.on("error", () => resolve({}));
  });
}
function registerRoutes(ctx, deps) {
  const { syncSwitches } = deps;
  const handler = guard("route", async (req, res) => {
    const path = pathOf(req);
    const method = req.method || "GET";
    const rel = path.slice(PREFIX2.length) || "/";
    if (method === "GET" && rel === "/state") {
      const [config, sessions, detected, alive] = await Promise.all([
        readConfig(),
        listSessions(),
        detectMemoryPlugins(),
        autoMemoryAlive()
      ]);
      return writeJson(res, 200, {
        ok: true,
        config,
        sessions,
        detected,
        autoMemoryAlive: alive,
        sanitize: selfTest(),
        version: "0.1.0"
      });
    }
    if (method === "GET" && rel === "/sessions") {
      return writeJson(res, 200, { ok: true, sessions: await listSessions() });
    }
    if (method === "GET" && rel === "/session") {
      const url = new URL(req.url, "http://127.0.0.1");
      const id = url.searchParams.get("id");
      const list = await listSessions();
      const entry = list.find((s) => s.id === id);
      if (!entry) return writeJson(res, 404, { ok: false, error: "not-found" });
      const events = await readSession(entry.file);
      return writeJson(res, 200, { ok: true, entry, events });
    }
    if (method === "GET" && rel === "/stats") {
      const list = await listSessions();
      const byStatus = {};
      const byVerdict = {};
      let rounds = 0;
      let questions = 0;
      let answered = 0;
      let corrections = 0;
      for (const s of list) {
        byStatus[s.status] = (byStatus[s.status] || 0) + 1;
        rounds += s.rounds || 0;
        const events = await readSession(s.file);
        for (const ev of events) {
          if (ev.type === "fit/ask") questions += (ev.questions || []).length;
          if (ev.type === "fit/answer") answered += (ev.answers || []).length;
          if (ev.type === "fit/feedback") {
            byVerdict[ev.verdict] = (byVerdict[ev.verdict] || 0) + 1;
            if (ev.verdict === "corrected") corrections++;
          }
        }
      }
      const totalVerdicts = Object.values(byVerdict).reduce((a, b) => a + b, 0);
      return writeJson(res, 200, {
        ok: true,
        sessions: list.length,
        byStatus,
        rounds,
        questions,
        answered,
        byVerdict,
        // 纠正率 = 样本信息量。越高越值得训练。
        correctionRate: totalVerdicts ? corrections / totalVerdicts : 0
      });
    }
    if (method === "GET" && rel === "/export") {
      const url = new URL(req.url, "http://127.0.0.1");
      const intentOnly = url.searchParams.get("intentOnly") !== "false";
      const list = await listSessions();
      const pairs = [];
      for (const s of list) {
        const events = await readSession(s.file);
        let utterance = "";
        let directions = [];
        const rounds = [];
        let conclusion = null;
        let finish2 = null;
        for (const ev of events) {
          if (ev.type === "fit/start") utterance = ev.utterance || "";
          if (ev.type === "fit/directions") directions = ev.directions || [];
          if (ev.type === "fit/ask") rounds.push({ index: ev.round, questions: ev.questions || [], answers: null });
          if (ev.type === "fit/answer") {
            const r0 = rounds.find((x) => x.index === ev.round);
            if (r0) r0.answers = ev.answers || [];
          }
          if (ev.type === "fit/propose") conclusion = ev.conclusion;
          if (ev.type === "fit/finish") finish2 = ev;
        }
        for (const r0 of rounds) {
          if (!r0.answers || !r0.answers.length) continue;
          for (const q of r0.questions) {
            const a = r0.answers.find((x) => x.id === q.id);
            if (!a) continue;
            const chosen = a.custom || (a.selected || []).join("、");
            if (!chosen) continue;
            const rejected = (q.options || []).map((o) => o.label).filter((l) => l !== chosen);
            if (!rejected.length) continue;
            pairs.push({
              prompt: utterance + (r0.index > 1 ? " [第" + r0.index + "轮]" : "") + "\n问：" + q.question,
              chosen,
              rejected,
              verdict: "accepted",
              scope: "intent",
              meta: { session: s.id, round: r0.index, questionId: q.id }
            });
          }
        }
        if (conclusion && conclusion.winner && directions.length > 1) {
          pairs.push({
            prompt: utterance + "\n（请判断用户最终想要哪一个方向）",
            chosen: conclusion.winner,
            rejected: directions.map((d) => d.label).filter((l) => l !== conclusion.winner),
            verdict: finish2 && finish2.accepted ? "accepted" : "rejected",
            scope: "intent",
            meta: { session: s.id, final: true, confidence: conclusion.confidence ?? null }
          });
        }
      }
      const out = intentOnly ? pairs.filter((p) => p.scope === "intent") : pairs;
      return writeJson(res, 200, {
        ok: true,
        count: out.length,
        intentOnly,
        jsonl: out.map((p) => JSON.stringify(p)).join("\n") + (out.length ? "\n" : "")
      });
    }
    if (method === "GET" && rel === "/config-export") {
      const cfg = await readConfig();
      return writeJson(res, 200, { ok: true, config: cfg, exportedAt: (/* @__PURE__ */ new Date()).toISOString() });
    }
    if (method === "POST" && rel === "/config-import") {
      const body = await readBody(req);
      const src = body && body.config || body || {};
      const allowed = ["injectContext", "writeMemory", "exposeTools", "localArchive", "panelOpenByDefault", "persistPanelOpen", "maxQuestionsPerRound", "maxRounds"];
      const patch = {};
      for (const k of allowed) if (k in src) patch[k] = src[k];
      const next = await writeConfig(patch);
      await syncSwitches();
      return writeJson(res, 200, { ok: true, config: next, applied: Object.keys(patch) });
    }
    if (method === "GET" && rel === "/detect") {
      return writeJson(res, 200, { ok: true, detected: await detectMemoryPlugins(), alive: await autoMemoryAlive() });
    }
    if (method === "POST" && rel === "/config") {
      const body = await readBody(req);
      const allowed = ["injectContext", "writeMemory", "exposeTools", "localArchive", "panelOpenByDefault", "persistPanelOpen", "maxQuestionsPerRound", "maxRounds"];
      const patch = {};
      for (const k of allowed) if (k in body) patch[k] = body[k];
      const next = await writeConfig(patch);
      await syncSwitches();
      log("config updated:", JSON.stringify(patch));
      return writeJson(res, 200, { ok: true, config: next });
    }
    if (method === "POST" && rel === "/start") {
      const body = await readBody(req);
      const sess = await beginFitting({
        workspace: String(body.workspace || ""),
        utterance: String(body.utterance || ""),
        anchor: body.node ? { node: String(body.node) } : null
      });
      if (Array.isArray(body.directions) && body.directions.length) {
        await recordDirections(sess, body.directions);
      }
      log("fit started from panel:", sess.id);
      return writeJson(res, 200, { ok: true, session: { id: sess.id, file: sess.file, createdAt: sess.createdAt } });
    }
    if (method === "POST" && rel === "/archive") {
      const body = await readBody(req);
      const sess = await loadSession(String(body.sessionId || ""));
      if (!sess) return writeJson(res, 404, { ok: false, error: "not-found" });
      await propose(sess, { winner: body.winner, confidence: body.confidence, intent: body.intent, text: body.note });
      await finish(sess, { accepted: body.accepted !== false, note: body.note });
      const cfg = await readConfig();
      let external = { ok: false, reason: "disabled" };
      if (cfg.writeMemory) external = await writeToAutoMemory(buildConclusionNote(sess, { note: body.note }));
      return writeJson(res, 200, { ok: true, local: true, external, writeMemory: cfg.writeMemory });
    }
    if (method === "POST" && rel === "/rename") {
      const body = await readBody(req);
      const list = await listSessions();
      const entry = list.find((s) => s.id === String(body.sessionId || ""));
      if (!entry) return writeJson(res, 404, { ok: false, error: "not-found" });
      entry.title = String(body.title || "").slice(0, 120);
      await writeIndex(list);
      return writeJson(res, 200, { ok: true, entry });
    }
    if (method === "DELETE" && rel === "/session") {
      const url = new URL(req.url, "http://127.0.0.1");
      const id = url.searchParams.get("id");
      const res2 = await deleteSession(id);
      return writeJson(res2.ok ? 200 : 404, res2);
    }
    return writeJson(res, 404, { ok: false, error: "unknown-route", path: rel, method });
  });
  try {
    const dispose = ctx.webServer.register({ kind: "prefix", path: PREFIX2, handler });
    log("routes registered at", PREFIX2);
    return typeof dispose === "function" ? [dispose] : [];
  } catch (e) {
    warn("route registration failed:", e && e.message);
    return [];
  }
}
async function loadSession(id) {
  const list = await listSessions();
  const entry = list.find((s) => s.id === id);
  if (!entry) return null;
  const events = await readSession(entry.file);
  const sess = {
    id: entry.id,
    file: entry.file,
    createdAt: entry.createdAt,
    workspace: entry.workspace,
    utterance: entry.utterance,
    anchor: null,
    rounds: [],
    directions: [],
    status: entry.status,
    conclusion: entry.conclusion
  };
  for (const ev of events) {
    if (ev.type === "fit/start") {
      sess.anchor = ev.anchor;
      sess.workspace = ev.workspace ?? sess.workspace;
    }
    if (ev.type === "fit/directions") sess.directions = ev.directions || [];
    if (ev.type === "fit/ask") sess.rounds.push({ index: ev.round, questions: ev.questions || [], answers: null, summary: "" });
    if (ev.type === "fit/answer") {
      const r = sess.rounds.find((x) => x.index === ev.round);
      if (r) {
        r.answers = ev.answers;
        r.summary = ev.summary || "";
      }
    }
    if (ev.type === "fit/propose") sess.conclusion = ev.conclusion;
  }
  return sess;
}

// src/node/index.js
var name = "memory-fitting-pre";
var inject = ["webServer", "tools"];
function apply(ctx, config) {
  let toolDisposers = [];
  let contextDisposer = null;
  function mountTools() {
    if (toolDisposers.length) return;
    const defs = toolDefs(ctx);
    for (const def of defs) {
      try {
        const d = ctx.tools.register(def);
        if (typeof d === "function") toolDisposers.push(d);
      } catch (e) {
        warn("tool register failed:", def.name, e && e.message);
      }
    }
    log("tools mounted:", defs.map((d) => d.name).join(", "));
  }
  function unmountTools() {
    for (const d of toolDisposers) {
      try {
        d();
      } catch {
      }
    }
    toolDisposers = [];
    log("tools unmounted");
  }
  function mountContextSection() {
    if (contextDisposer) return;
    try {
      const d = ctx.systemPrompt.section({
        name: "dsh:memory-fitting",
        order: 9950,
        text: () => [
          "当用户需求模糊、反复改口、或说「你帮我看着办」时：",
          "调用 memory_fit_start 启动一次意图拟合（先预定方向，再批量提问，收敛后提案）。",
          "拟合阶段只做意图理解与澄清，禁止执行任何实际动作；只有用户确认后才动手。"
        ].join("\n")
      });
      contextDisposer = typeof d === "function" ? d : null;
      log("context section mounted");
    } catch (e) {
      warn("systemPrompt unavailable:", e && e.message);
    }
  }
  function unmountContextSection() {
    if (!contextDisposer) return;
    try {
      contextDisposer();
    } catch {
    }
    contextDisposer = null;
    log("context section unmounted");
  }
  async function syncSwitches() {
    const cfg = await readConfig();
    if (cfg.exposeTools) mountTools();
    else unmountTools();
    if (cfg.injectContext) mountContextSection();
    else unmountContextSection();
    return cfg;
  }
  ctx.effect(() => {
    syncSwitches().catch((e) => warn("initial sync failed:", e && e.message));
    return () => {
      unmountTools();
      unmountContextSection();
    };
  }, "dsh-memory-fitting: switches");
  try {
    registerRoutes(ctx, { syncSwitches });
  } catch (e) {
    warn("routes registration failed:", e && e.message);
  }
}
function textResult() {
  return {
    schema: { type: "string" },
    render: (_args, v) => [{ type: "text", text: String(v) }]
  };
}
function toolDefs(ctx) {
  return [fitStartTool(ctx), fitAskTool(ctx), fitArchiveTool(), fitHistoryTool()];
}
async function loadSession2(id) {
  const list = await listSessions();
  const entry = list.find((s) => s.id === id);
  if (!entry) return null;
  const events = await readSession(entry.file);
  const sess = {
    id: entry.id,
    file: entry.file,
    createdAt: entry.createdAt,
    workspace: entry.workspace,
    utterance: entry.utterance,
    anchor: null,
    rounds: [],
    directions: [],
    status: entry.status,
    conclusion: entry.conclusion
  };
  for (const ev of events) {
    if (ev.type === "fit/start") {
      sess.anchor = ev.anchor;
      sess.workspace = ev.workspace ?? sess.workspace;
    }
    if (ev.type === "fit/directions") sess.directions = ev.directions || [];
    if (ev.type === "fit/ask") sess.rounds.push({ index: ev.round, questions: ev.questions || [], answers: null, summary: "" });
    if (ev.type === "fit/answer") {
      const r = sess.rounds.find((x) => x.index === ev.round);
      if (r) {
        r.answers = ev.answers;
        r.summary = ev.summary || "";
      }
    }
    if (ev.type === "fit/propose") sess.conclusion = ev.conclusion;
  }
  return sess;
}
function fitStartTool() {
  return {
    name: "memory_fit_start",
    description: "启动一次「记忆拟合」：当用户需求模糊、自己也说不清要什么时，先预定 3-5 个可能的方向（预测其意图），再通过批量提问逐步收敛。仅做意图理解，不执行任何实际操作。收敛后需用户确认。",
    parameters: {
      type: "object",
      properties: {
        utterance: { type: "string", description: "触发本次拟合的用户原话或需求描述" },
        workspace: { type: "string", description: "当前工作区路径，用于归档锚点" },
        node: { type: "string", description: "工作节点名（可留空，收敛后回填）" },
        directions: {
          type: "array",
          description: "你预定的方向，3-5 个。每个含 label 与 detail（若成立会有什么表现）",
          items: {
            type: "object",
            properties: { label: { type: "string" }, detail: { type: "string" } },
            required: ["label"]
          }
        }
      },
      required: ["utterance"]
    },
    output: textResult(),
    timeoutMs: 3e4,
    async execute(args) {
      const cfg = await readConfig();
      if (!cfg.localArchive) {
        return "本地留档当前处于关闭状态（memory-fitting 设置页可开）。已忽略本次拟合启动，以免产生无处存放的会话。";
      }
      const sess = await beginFitting({
        workspace: String(args?.workspace || ""),
        utterance: String(args?.utterance || ""),
        anchor: { node: args?.node ? String(args.node) : null }
      });
      if (Array.isArray(args?.directions) && args.directions.length) {
        await recordDirections(sess, args.directions);
      }
      log("fit started:", sess.id);
      const d = (sess.directions || []).map((x, i) => i + 1 + ". " + x.label).join("\n");
      return [
        "拟合会话已建立：" + sess.id,
        d ? "你预定的方向：\n" + d : "（尚未预定方向，请先写下 3-5 个方向）",
        "",
        "下一步：调用 memory_fit_ask 提出本轮 2-4 个问题（会暂停等待用户作答）。"
      ].join("\n");
    }
  };
}
function fitAskTool(ctx) {
  return {
    name: "memory_fit_ask",
    description: "在拟合会话中提出一轮问题（2-4 个），暂停并等待用户作答，返回全部答案。答案会写入本地留档。若用户中途取消，返回未完成状态。",
    parameters: {
      type: "object",
      properties: {
        sessionId: { type: "string", description: "memory_fit_start 返回的会话 id" },
        questions: {
          type: "array",
          description: "本轮要问的问题，2-4 个",
          items: {
            type: "object",
            properties: {
              id: { type: "string" },
              question: { type: "string" },
              header: { type: "string" },
              options: {
                type: "array",
                items: {
                  type: "object",
                  properties: { label: { type: "string" }, description: { type: "string" } },
                  required: ["label"]
                }
              },
              multiSelect: { type: "boolean" }
            },
            required: ["id", "question"]
          }
        }
      },
      required: ["sessionId", "questions"]
    },
    output: textResult(),
    timeoutMs: 6e5,
    async execute(args, exec) {
      const sessionId = String(args?.sessionId || "");
      const questions = Array.isArray(args?.questions) ? args.questions : [];
      if (!sessionId) return "缺少 sessionId。请先调用 memory_fit_start。";
      if (!questions.length) return "本轮没有问题可问。";
      const cfg = await readConfig();
      if (!cfg.localArchive) return "本地留档已关闭，拟合流程暂停。请在 memory-fitting 设置页开启「本地留档」。";
      const sess = await loadSession2(sessionId);
      if (!sess) return "找不到会话 " + sessionId + "（可能已被清理）。";
      if (sess.rounds.length >= cfg.maxRounds) {
        return "已达轮数上限（" + cfg.maxRounds + " 轮）。请直接收敛提案，或由用户在悬窗调高上限。";
      }
      const uq = typeof ctx.get === "function" ? ctx.get("userQuestions") : null;
      if (!uq || typeof uq.ask !== "function") {
        return "宿主没有提供 userQuestions 能力，无法向用户提问。请检查 dsh-tool-ask-user 是否启用。";
      }
      const capped = questions.slice(0, Math.max(1, Math.min(cfg.maxQuestionsPerRound, 8)));
      const round = await recordQuestions(sess, capped);
      let answers;
      try {
        const res = await uq.ask({
          questions: capped.map((q) => ({
            id: String(q.id),
            question: String(q.question),
            ...q.header ? { header: String(q.header) } : {},
            ...Array.isArray(q.options) ? { options: q.options } : {},
            ...q.multiSelect ? { multiSelect: true } : {}
          })),
          ...exec && exec.agent ? { agent: exec.agent } : {},
          ...exec && exec.signal ? { signal: exec.signal } : {}
        });
        answers = res && res.answers ? res.answers : [];
      } catch (e) {
        warn("ask failed:", e && e.message);
        return "用户未完成作答（" + (e && e.message ? e.message : "cancelled") + "）。已答内容保留在本地留档。";
      }
      await recordAnswers(sess, round.index, answers);
      await recordFeedback(sess, {
        context: sess.utterance,
        modelDid: capped.map((q) => q.question).join(" / "),
        userSaid: (answers || []).map((a) => a.custom || (a.selected || []).join("、")).join(" / "),
        verdict: "accepted",
        preference: ""
      }).catch(() => {
      });
      const lines = capped.map((q) => {
        const a = answers.find((x) => x.id === q.id);
        const picked = a ? a.custom || (a.selected || []).join("、") : "（未答）";
        return "Q: " + q.question + "\nA: " + picked;
      });
      return [
        "本轮（第 " + round.index + " 轮 / 上限 " + cfg.maxRounds + "）作答结果：",
        lines.join("\n"),
        "",
        "下一步：更新方向与可信度（展示给用户），然后决定继续提问还是收敛提案。"
      ].join("\n");
    }
  };
}
function fitArchiveTool() {
  return {
    name: "memory_fit_archive",
    description: "把一个拟合会话的收敛结论归档。本地留档始终写入；写入外部记忆插件受 writeMemory 开关控制（默认关闭）。",
    parameters: {
      type: "object",
      properties: {
        sessionId: { type: "string" },
        winner: { type: "string", description: "收敛到的方向" },
        intent: { type: "string", description: "清晰的用户目标" },
        confidence: { type: "number" },
        accepted: { type: "boolean", description: "用户是否确认了该结论" },
        note: { type: "string" },
        rejectedReason: {
          type: "string",
          description: '用户【拒绝】该提案时，说明错在哪（选了另一个方向？还是"都不对"？）。这是训练价值最高的信号，请务必填写。'
        }
      },
      required: ["sessionId", "winner"]
    },
    output: textResult(),
    timeoutMs: 3e4,
    async execute(args) {
      const sess = await loadSession2(String(args?.sessionId || ""));
      if (!sess) return "找不到该会话。";
      await propose(sess, {
        winner: args.winner,
        confidence: args.confidence,
        intent: args.intent,
        text: args.note
      });
      if (args.accepted === false) {
        await recordFeedback(sess, {
          context: sess.utterance,
          modelDid: String(args.winner || ""),
          userSaid: String(args.note || ""),
          verdict: "corrected",
          preference: String(args.rejectedReason || ""),
          scope: "intent",
          rejectedReason: String(args.rejectedReason || "用户未说明"),
          deliberate: true
        }).catch(() => {
        });
      }
      await finish(sess, { accepted: args.accepted !== false, note: args.note });
      const cfg = await readConfig();
      if (!cfg.writeMemory) {
        return "会话 " + sess.id + " 已写入本地留档。记忆写入开关处于关闭状态，未写入外部记忆插件（默认值，可在悬窗设置里打开）。";
      }
      const external = await writeToAutoMemory(buildConclusionNote(sess, { note: args.note }));
      return external.ok ? "会话 " + sess.id + " 已归档并写入记忆插件" + (external.sanitized ? "（安全改写 " + external.sanitized + " 处）" : "") + "。" : "会话 " + sess.id + " 已本地归档；记忆插件写入失败：" + external.reason + "（本地留档不受影响）。";
    }
  };
}
function fitHistoryTool() {
  return {
    name: "memory_fit_history",
    description: "查看历史记忆拟合留档（最近若干条收敛结论）。用户问「上次关于 X 拟合出什么了」时调用。",
    parameters: {
      type: "object",
      properties: { limit: { type: "number", description: "返回条数，默认 8，最大 30" } },
      required: []
    },
    output: textResult(),
    timeoutMs: 15e3,
    async execute(args) {
      const limit = Math.max(1, Math.min(Number(args?.limit) || 8, 30));
      const list = await listSessions();
      if (!list.length) return "还没有任何拟合留档。";
      return list.slice(0, limit).map((s) => {
        const w = s.title || s.conclusion && s.conclusion.winner || "（未收敛）";
        return "- [" + String(s.createdAt || "").slice(0, 16).replace("T", " ") + "] " + w + " ← 「" + String(s.utterance || "").slice(0, 40) + "」 (" + s.status + ")";
      }).join("\n");
    }
  };
}
export {
  apply,
  inject,
  name
};
